config/routes.rb
Contacts::Application.routes.draw do
  root :to => 'home#index'

  # Account management
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' },
    skip: 'registrations'

  devise_scope :user do
    patch '/users', to: 'registrations#update', as: :user_registration
    put   '/users', to: 'registrations#update', as: nil
  end

  get 'profile' => 'profile#index', :as => :profile

  # User page
  get  'u/:long_token' => 'contact#index', :as => :user_page
  post 'u/:long_token' => 'contact#add_contact'

  # Errors
  get '404' => 'error#error_404', as: :error_404
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'layouts/home'

  def index
  end
end

app/views/home/index.html.haml
.feature.main
  %h1 Contact exchange
  %p.lead Give a URL, get a contact. It's that simple.
  - if !current_user
    = link_to 'Sign up with Google', omniauth_authorize_path(:user, :google_oauth2), :class => 'btn btn-lg btn-success'
  - else
    = link_to 'Go to your profile', profile_path, :class => 'btn btn-lg btn-info'

%hr

.row.features
  .col-md-4
    %h4 Simple
    %p Register, get a URL, give it to anyone who's contact you want. When they fill up the form, the new contact is instantly synced to your mobile device.
  .col-md-4
    %h4 Seamless
    %p Seamlessly and instantly syncs contacts with all major mobile operating systems: <strong>iOS</strong>, <strong>Android</strong> and <strong>Windows Phone</strong>.
  .col-md-4
    %h4 Secure
    %p Your URL contains a long hash that is almost impossible to guess, so only the people you trust will be able to add their contact.