config/routes.rb
Contacts::Application.routes.draw do
  root :to => 'home#index'

  # Account management
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' },
    skip: 'registrations'

  devise_scope :user do
    patch '/users', to: 'registrations#update', as: :user_registration
    put   '/users', to: 'registrations#update', as: nil
  end

  get 'profile' => 'profile#index', :as => :profile

  # User page
  get  'u/:long_token' => 'contact#index', :as => :user_page
  post 'u/:long_token' => 'contact#add_contact'

  # Errors
  get '404' => 'error#error_404', as: :error_404
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  layout 'layouts/card'

  # GET /users/1
  def index
    @user = User.find_by_long_token(params[:long_token]) || not_found
  end

  # POST /user/1
  def add_contact
    user = User.find_by_long_token(params[:long_token]) || not_found

    response_status = user.add_contact(contact_params)

    if response_status
      render json: { toast: {
        type: :success,
        message: 'Contact added'
      }}
    else
      render json: { error: 'Failed to add the contact' }, status: :internal_server_error
    end
  end

  private

  def contact_params
    params.permit(:first_name, :last_name, :phone)
  end
end

app/views/contact/_contact_form.html.haml
= form_tag(user_page_url(@user.long_token), method: :post, remote: true, 'data-parsley-validate' => true) do
  .form-group
    = text_field_tag :first_name, nil, placeholder: 'First name', autocomplete: :off, class: 'form-control input-lg', 'data-parsley-required' => true, 'data-parsley-minlength' => 2
  
  .form-group
    = text_field_tag :last_name, nil, placeholder: 'Last name', autocomplete: :off, class: 'form-control input-lg', 'data-parsley-required' => true, 'data-parsley-minlength' => 2
  
  .form-group
    = text_field_tag :phone, nil, placeholder: 'Phone number', autocomplete: :off, class: 'form-control input-lg', 'data-parsley-required' => true, 'data-parsley-pattern' => '+?\d{6,}'

  .form-group
    %button{ type: :submit, class: 'btn btn-block btn-primary btn-lg ladda-button', 'data-style' => 'zoom-out' }
      %span.ladda-label Add contact

app/views/contact/index.html.haml
%h2.heading= @user.name
%hr
= render 'contact_form'